doge_facebook_admin:
    resource: "@DogeFacebookBundle/Resources/config/routing.yml"
    prefix:   /admin

doge_facebook_front:
    resource: "@DogeFacebookBundle/Resources/config/routing_front.yml"
    prefix:   /app

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /admin

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /app/connect
    requirements:
        _scheme: https

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /app/login

facebook_login:
    pattern: /app/login/check-facebook