# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        admin:
            pattern: ^/admin/.*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /admin/login
                check_path: /admin/login_check
                failure_path: /admin/login
            logout:       true
            anonymous:    true

        main:
            context: user
            pattern: /.*
            oauth:
                resource_owners:
                    facebook: /login/check-facebook
                login_path: /connect
                failure_path: /connect
                oauth_user_provider:
                    service: doge.oauth.user_provider
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN