# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    providers:
        doge_user_provider:
            id: doge.oauth.user_provider
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        admin:
            pattern: ^/admin/.*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /admin/login
                check_path: /admin/login_check
                failure_path: /admin/login
            logout:       true
            anonymous:    true

        main:
            context: user
            pattern: ^/app/.*
            oauth:
                resource_owners:
                    facebook: /app/login/check-facebook
                login_path: /app/login
                failure_path: /app/connect
                check_path: /app/login_check
                oauth_user_provider:
                    service: doge.oauth.user_provider
            logout:
                path:   /app/logout
                target: /app
            anonymous: true

    access_control:
        - { path: ^/app/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app/connect/facebook, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app/upload, role: ROLE_USER }
        - { path: ^/app/gallery, role: ROLE_USER }
        - { path: ^/app/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN