doge_facebook__test_homepage:
    path:     /admin/hello/{name}
    defaults: { _controller: DogeFacebookBundle:Default:index }

doge_facebook_homepage:
    path:     /
    defaults: { _controller: DogeFacebookBundle:Home:new }

doge_facebook_slideshow:
    path: /slideshow
    defaults: { _controller: DogeFacebookBundle:Home:slideshow }

doge_facebook_upload:
    path: /upload
    defaults: { _controller: DogeFacebookBundle:Home:uploadPhoto }

doge_facebook_admin_index:
    path:     /admin/index
    defaults: { _controller: DogeFacebookBundle:Admin:index }