doge_facebook__test_homepage:
    path:     /admin/hello/{name}
    defaults: { _controller: DogeFacebookBundle:Default:index }

doge_facebook_admin_index:
    path:     /index
    defaults: { _controller: DogeFacebookBundle:Admin:index }