doge_facebook_homepage:
    path:     /
    defaults: { _controller: DogeFacebookBundle:Home:new }

doge_facebook_upload:
    path: /upload
    defaults: { _controller: DogeFacebookBundle:Gallery:uploadPhoto }

doge_facebook_gallery:
    path: /gallery
    defaults: { _controller: DogeFacebookBundle:Gallery:gallery }

doge_facebook_test_homepage:
    path:     /test
    defaults: { _controller: DogeFacebookBundle:Default:test }

doge_facebook_photo_from_id:
    path: /album/{id}
    defaults: { _controller: DogeFacebookBundle:Gallery:getPhotosFromAlbumId }

doge_facebook_terms_conditions:
    path:     /terms-conditions
    defaults: { _controller: DogeFacebookBundle:Home:terms }


doge_facebook_rules_contest:
    path:     /rules-contest
    defaults: { _controller: DogeFacebookBundle:Home:rules}