services:
    doge_facebook.session.helper:
        class: Doge\FacebookBundle\Helper\Facebook\FacebookSessionHelper
        scope: request
        arguments: [ @request, @router, @security.token_storage, %doge_facebook.appId%, %doge_facebook.appSecret% ]

    doge.oauth.user_provider:
        class: Doge\FacebookBundle\Provider\OauthProvider
        arguments: [@fos_user.user_manager,{facebook: facebookId}]

    doge.facebook_session:
        class: Doge\FacebookBundle\Facebook\FacebookSession
        arguments: [ @security.token_storage ]
