services:
    doge_facebook.session.helper:
        class: Doge\FacebookBundle\Helper\Facebook\FacebookSessionHelper
        scope: request
        arguments: [ @request, @router, %doge_facebook.appId%, %doge_facebook.appSecret% ]
